# Generated by Django 5.1.4 on 2026-10-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
